"""Download IRIS checkpoints from Google Drive.

Run this script to download all required checkpoint files for running
the notebooks locally. The checkpoints are hosted on Google Drive and
are required for notebooks 03-08.

Usage:
    python checkpoints/download_checkpoints.py

Required files (generated by notebooks 01-05 on Colab):
    - sae_d10240_lambda1e-04.pt   (~200 MB) — Trained sparse autoencoder (GPT-2 Large)
    - j1_activations.npz           (~46 MB) — Layer 35 activations (notebook 01)
    - j2_activations.npz           (~46 MB) — Layer 35 activations (notebook 02)
    - sensitivity_scores.npy       (~80 KB) — Per-feature sensitivity scores
    - feature_matrix.npy           (~40 MB) — SAE feature activations for dataset

If running on Google Colab, these files are already available at:
    /content/drive/MyDrive/iris/checkpoints/

For local runs or submission review, copy them from the Colab Drive
into the checkpoints/ directory of this repository.
"""

import sys
from pathlib import Path

CHECKPOINT_DIR = Path(__file__).parent
REQUIRED_FILES = [
    "sae_d10240_lambda1e-04.pt",
    "j2_activations.npz",
    "sensitivity_scores.npy",
    "feature_matrix.npy",
]

OPTIONAL_FILES = [
    "j1_activations.npz",  # Only needed for notebook 01-02 reruns
]


def check_checkpoints() -> bool:
    """Verify all required checkpoint files are present."""
    all_present = True
    for fname in REQUIRED_FILES:
        path = CHECKPOINT_DIR / fname
        if path.exists():
            size_mb = path.stat().st_size / (1024 * 1024)
            print(f"  [OK] {fname} ({size_mb:.1f} MB)")
        else:
            print(f"  [MISSING] {fname}")
            all_present = False

    for fname in OPTIONAL_FILES:
        path = CHECKPOINT_DIR / fname
        if path.exists():
            size_mb = path.stat().st_size / (1024 * 1024)
            print(f"  [OK] {fname} ({size_mb:.1f} MB) (optional)")
        else:
            print(f"  [--] {fname} (optional, not required)")

    return all_present


if __name__ == "__main__":
    print("IRIS Checkpoint Verification")
    print("=" * 40)
    print(f"Checkpoint directory: {CHECKPOINT_DIR.resolve()}\n")

    if check_checkpoints():
        print("\nAll required checkpoints present.")
    else:
        print("\nMissing checkpoints! To obtain them:")
        print("  1. Run notebooks 01-05 on Google Colab, OR")
        print("  2. Copy from Google Drive: /content/drive/MyDrive/iris/checkpoints/")
        print("  3. Place files in:", CHECKPOINT_DIR.resolve())
        sys.exit(1)
